export const airCompSchema = {
  key: "airComp",
  label: "공기조화기(AHU)",
  checklist: [
    "유지 관리 점검표",
    "외부 케이싱 부식/손상/변형 상태",
    "수동댐퍼(OA/EA/RA) 동작 상태",
    "동파방지장치 작동 상태",
    "공기조화기(송풍기) 풍량 상태",
    "폐열회수장치 작동 상태",
    "소음/진동 상태",
    "필터 오염 상태",
  ],
  photos: [
    { id: "bms", label: "자동제어 화면 상태" },
    { id: "ea_damper", label: "EA 댐퍼 개도율" },
    { id: "oa_damper", label: "OA 댐퍼 개도율" },
    { id: "casing_state", label: "외부 케이싱 부식·손상·변형 상태" },
    { id: "anti_freeze",  label: "동파방지장치 작동 상태" },
    { id: "ra_noise", label: "RA 모터 측 소음 측정" },
    { id: "ra_vibration", label: "RA 모터 측 진동 측정" },
    { id: "ra_airflow", label: "모터 측 풍량 측정" },
    { id: "ra_dp", label: "모터 측 차압 측정" },
    { id: "sa_voltage", label: "SA 모터 전압 측정" },
    { id: "sa_current2", label: "SA 모터 2차측 전류 측정" },
    { id: "ra_voltage", label: "RA 모터 전압 측정" },
    { id: "ra_current2", label: "RA 모터 2차측 전류 측정" },
    { id: "sa_inverter", label: "SA 인버터 판넬 수치" },
    { id: "ra_inverter", label: "RA 인버터 판넬 수치" },
  ],
};
